//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQISet {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AqiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AqiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AQISet.AqiResource", typeof(AqiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 合并模式 的本地化字符串。
        /// </summary>
        internal static string ModeMerger {
            get {
                return ResourceManager.GetString("ModeMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通模式 的本地化字符串。
        /// </summary>
        internal static string ModeNormal {
            get {
                return ResourceManager.GetString("ModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立模式 的本地化字符串。
        /// </summary>
        internal static string ModeSelf {
            get {
                return ResourceManager.GetString("ModeSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束运行 的本地化字符串。
        /// </summary>
        internal static string Runner_End {
            get {
                return ResourceManager.GetString("Runner_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始运行 的本地化字符串。
        /// </summary>
        internal static string Runner_Run {
            get {
                return ResourceManager.GetString("Runner_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        internal static string SomeTime_DAY {
            get {
                return ResourceManager.GetString("SomeTime_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7天 的本地化字符串。
        /// </summary>
        internal static string SomeTime_DAY7 {
            get {
                return ResourceManager.GetString("SomeTime_DAY7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每 的本地化字符串。
        /// </summary>
        internal static string SomeTime_Every {
            get {
                return ResourceManager.GetString("SomeTime_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string SomeTime_Hour {
            get {
                return ResourceManager.GetString("SomeTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12小时 的本地化字符串。
        /// </summary>
        internal static string SomeTime_Hour12 {
            get {
                return ResourceManager.GetString("SomeTime_Hour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string SomeTime_Minute {
            get {
                return ResourceManager.GetString("SomeTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30分钟 的本地化字符串。
        /// </summary>
        internal static string SomeTime_Minute30 {
            get {
                return ResourceManager.GetString("SomeTime_Minute30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区级数据源 的本地化字符串。
        /// </summary>
        internal static string SourceArea {
            get {
                return ResourceManager.GetString("SourceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市级数据源 的本地化字符串。
        /// </summary>
        internal static string SourceCity {
            get {
                return ResourceManager.GetString("SourceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家数据源 的本地化字符串。
        /// </summary>
        internal static string SourceNational {
            get {
                return ResourceManager.GetString("SourceNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非数据源 的本地化字符串。
        /// </summary>
        internal static string SourceNone {
            get {
                return ResourceManager.GetString("SourceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他数据源 的本地化字符串。
        /// </summary>
        internal static string SourceOther {
            get {
                return ResourceManager.GetString("SourceOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省级数据源 的本地化字符串。
        /// </summary>
        internal static string SourceProvioncial {
            get {
                return ResourceManager.GetString("SourceProvioncial", resourceCulture);
            }
        }
    }
}
