//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQIPlugin.LN.WSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSReference.AirQualityServiceSoap")]
    public interface AirQualityServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStationAQIDetailByStationCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.StationDetail GetStationAQIDetailByStationCode(string stationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get48Hours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] Get48Hours(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAQIDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] GetAQIDetail(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCity30Days", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] GetCity30Days(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get30Days", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] Get30Days(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCity48Hours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] GetCity48Hours(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        string[] GetCityDetail(string code);
        
        // CODEGEN: 参数“GetReportCityAQIListResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportCityAQIList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.GetReportCityAQIListResponse GetReportCityAQIList(AQIPlugin.LN.WSReference.GetReportCityAQIListRequest request);
        
        // CODEGEN: 参数“GetReportPointAQIResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportPointAQI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.GetReportPointAQIResponse GetReportPointAQI(AQIPlugin.LN.WSReference.GetReportPointAQIRequest request);
        
        // CODEGEN: 参数“GetReportPointAQIListResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportPointAQIList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.GetReportPointAQIListResponse GetReportPointAQIList(AQIPlugin.LN.WSReference.GetReportPointAQIListRequest request);
        
        // CODEGEN: 参数“getRJNDResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRJND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.getRJNDResponse getRJND(AQIPlugin.LN.WSReference.getRJNDRequest request);
        
        // CODEGEN: 参数“getZHZSResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getZHZS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AQICityStation))]
        AQIPlugin.LN.WSReference.getZHZSResponse getZHZS(AQIPlugin.LN.WSReference.getZHZSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StationDetail : AQICityStation {
        
        private KeyValuePairOfStringDouble primaryPollutantField;
        
        private PollutantDetail detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KeyValuePairOfStringDouble PrimaryPollutant {
            get {
                return this.primaryPollutantField;
            }
            set {
                this.primaryPollutantField = value;
                this.RaisePropertyChanged("PrimaryPollutant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PollutantDetail Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringDouble : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IAQIEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pollutantNameField;
        
        private double iAQIField;
        
        private string iAQIColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PollutantName {
            get {
                return this.pollutantNameField;
            }
            set {
                this.pollutantNameField = value;
                this.RaisePropertyChanged("PollutantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double IAQI {
            get {
                return this.iAQIField;
            }
            set {
                this.iAQIField = value;
                this.RaisePropertyChanged("IAQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IAQIColor {
            get {
                return this.iAQIColorField;
            }
            set {
                this.iAQIColorField = value;
                this.RaisePropertyChanged("IAQIColor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PollutantDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double valueField;
        
        private double aQIField;
        
        private string unitField;
        
        private string codeField;
        
        private string nameField;
        
        private int levelField;
        
        private System.DateTime lastUpdateTimeField;
        
        private double sO2Field;
        
        private double nO2Field;
        
        private double pM1024Field;
        
        private double pM10Field;
        
        private double o3Field;
        
        private double o38Field;
        
        private double coField;
        
        private double pM25Field;
        
        private double pM2524Field;
        
        private double iAQI_SO2Field;
        
        private double iAQI_NO2Field;
        
        private double iAQI_PM1024Field;
        
        private double iAQI_PM2524Field;
        
        private double iAQI_O3Field;
        
        private double iAQI_O38Field;
        
        private double iAQI_COField;
        
        private IAQIEntity[] iAQIListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double AQI {
            get {
                return this.aQIField;
            }
            set {
                this.aQIField = value;
                this.RaisePropertyChanged("AQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime LastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
                this.RaisePropertyChanged("LastUpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double SO2 {
            get {
                return this.sO2Field;
            }
            set {
                this.sO2Field = value;
                this.RaisePropertyChanged("SO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double NO2 {
            get {
                return this.nO2Field;
            }
            set {
                this.nO2Field = value;
                this.RaisePropertyChanged("NO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double PM1024 {
            get {
                return this.pM1024Field;
            }
            set {
                this.pM1024Field = value;
                this.RaisePropertyChanged("PM1024");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double PM10 {
            get {
                return this.pM10Field;
            }
            set {
                this.pM10Field = value;
                this.RaisePropertyChanged("PM10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double O3 {
            get {
                return this.o3Field;
            }
            set {
                this.o3Field = value;
                this.RaisePropertyChanged("O3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double O38 {
            get {
                return this.o38Field;
            }
            set {
                this.o38Field = value;
                this.RaisePropertyChanged("O38");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
                this.RaisePropertyChanged("CO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double PM25 {
            get {
                return this.pM25Field;
            }
            set {
                this.pM25Field = value;
                this.RaisePropertyChanged("PM25");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double PM2524 {
            get {
                return this.pM2524Field;
            }
            set {
                this.pM2524Field = value;
                this.RaisePropertyChanged("PM2524");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double IAQI_SO2 {
            get {
                return this.iAQI_SO2Field;
            }
            set {
                this.iAQI_SO2Field = value;
                this.RaisePropertyChanged("IAQI_SO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double IAQI_NO2 {
            get {
                return this.iAQI_NO2Field;
            }
            set {
                this.iAQI_NO2Field = value;
                this.RaisePropertyChanged("IAQI_NO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double IAQI_PM1024 {
            get {
                return this.iAQI_PM1024Field;
            }
            set {
                this.iAQI_PM1024Field = value;
                this.RaisePropertyChanged("IAQI_PM1024");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double IAQI_PM2524 {
            get {
                return this.iAQI_PM2524Field;
            }
            set {
                this.iAQI_PM2524Field = value;
                this.RaisePropertyChanged("IAQI_PM2524");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public double IAQI_O3 {
            get {
                return this.iAQI_O3Field;
            }
            set {
                this.iAQI_O3Field = value;
                this.RaisePropertyChanged("IAQI_O3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public double IAQI_O38 {
            get {
                return this.iAQI_O38Field;
            }
            set {
                this.iAQI_O38Field = value;
                this.RaisePropertyChanged("IAQI_O38");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double IAQI_CO {
            get {
                return this.iAQI_COField;
            }
            set {
                this.iAQI_COField = value;
                this.RaisePropertyChanged("IAQI_CO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=23)]
        public IAQIEntity[] IAQIList {
            get {
                return this.iAQIListField;
            }
            set {
                this.iAQIListField = value;
                this.RaisePropertyChanged("IAQIList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StationDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AQICityStation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string cityNameField;
        
        private string stationIDField;
        
        private string sMarginField;
        
        private string positionNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("CityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StationID {
            get {
                return this.stationIDField;
            }
            set {
                this.stationIDField = value;
                this.RaisePropertyChanged("StationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SMargin {
            get {
                return this.sMarginField;
            }
            set {
                this.sMarginField = value;
                this.RaisePropertyChanged("SMargin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
                this.RaisePropertyChanged("PositionName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportCityAQIList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportCityAQIListRequest {
        
        public GetReportCityAQIListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportCityAQIListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportCityAQIListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetReportCityAQIListResult;
        
        public GetReportCityAQIListResponse() {
        }
        
        public GetReportCityAQIListResponse(string[][] GetReportCityAQIListResult) {
            this.GetReportCityAQIListResult = GetReportCityAQIListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportPointAQI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportPointAQIRequest {
        
        public GetReportPointAQIRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportPointAQIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportPointAQIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetReportPointAQIResult;
        
        public GetReportPointAQIResponse() {
        }
        
        public GetReportPointAQIResponse(string[][] GetReportPointAQIResult) {
            this.GetReportPointAQIResult = GetReportPointAQIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportPointAQIList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportPointAQIListRequest {
        
        public GetReportPointAQIListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportPointAQIListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportPointAQIListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetReportPointAQIListResult;
        
        public GetReportPointAQIListResponse() {
        }
        
        public GetReportPointAQIListResponse(string[][] GetReportPointAQIListResult) {
            this.GetReportPointAQIListResult = GetReportPointAQIListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRJND", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getRJNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string enddate;
        
        public getRJNDRequest() {
        }
        
        public getRJNDRequest(string startDate, string enddate) {
            this.startDate = startDate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRJNDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getRJNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] getRJNDResult;
        
        public getRJNDResponse() {
        }
        
        public getRJNDResponse(string[][] getRJNDResult) {
            this.getRJNDResult = getRJNDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZHZS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getZHZSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string enddate;
        
        public getZHZSRequest() {
        }
        
        public getZHZSRequest(string startDate, string enddate) {
            this.startDate = startDate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZHZSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getZHZSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] getZHZSResult;
        
        public getZHZSResponse() {
        }
        
        public getZHZSResponse(string[][] getZHZSResult) {
            this.getZHZSResult = getZHZSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirQualityServiceSoapChannel : AQIPlugin.LN.WSReference.AirQualityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirQualityServiceSoapClient : System.ServiceModel.ClientBase<AQIPlugin.LN.WSReference.AirQualityServiceSoap>, AQIPlugin.LN.WSReference.AirQualityServiceSoap {
        
        public AirQualityServiceSoapClient() {
        }
        
        public AirQualityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirQualityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirQualityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirQualityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AQIPlugin.LN.WSReference.StationDetail GetStationAQIDetailByStationCode(string stationCode) {
            return base.Channel.GetStationAQIDetailByStationCode(stationCode);
        }
        
        public string[] Get48Hours(string pcode) {
            return base.Channel.Get48Hours(pcode);
        }
        
        public string[] GetAQIDetail(string pcode) {
            return base.Channel.GetAQIDetail(pcode);
        }
        
        public string[] GetCity30Days(string code) {
            return base.Channel.GetCity30Days(code);
        }
        
        public string[] Get30Days(string pcode) {
            return base.Channel.Get30Days(pcode);
        }
        
        public string[] GetCity48Hours(string code) {
            return base.Channel.GetCity48Hours(code);
        }
        
        public string[] GetCityDetail(string code) {
            return base.Channel.GetCityDetail(code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AQIPlugin.LN.WSReference.GetReportCityAQIListResponse AQIPlugin.LN.WSReference.AirQualityServiceSoap.GetReportCityAQIList(AQIPlugin.LN.WSReference.GetReportCityAQIListRequest request) {
            return base.Channel.GetReportCityAQIList(request);
        }
        
        public string[][] GetReportCityAQIList() {
            AQIPlugin.LN.WSReference.GetReportCityAQIListRequest inValue = new AQIPlugin.LN.WSReference.GetReportCityAQIListRequest();
            AQIPlugin.LN.WSReference.GetReportCityAQIListResponse retVal = ((AQIPlugin.LN.WSReference.AirQualityServiceSoap)(this)).GetReportCityAQIList(inValue);
            return retVal.GetReportCityAQIListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AQIPlugin.LN.WSReference.GetReportPointAQIResponse AQIPlugin.LN.WSReference.AirQualityServiceSoap.GetReportPointAQI(AQIPlugin.LN.WSReference.GetReportPointAQIRequest request) {
            return base.Channel.GetReportPointAQI(request);
        }
        
        public string[][] GetReportPointAQI() {
            AQIPlugin.LN.WSReference.GetReportPointAQIRequest inValue = new AQIPlugin.LN.WSReference.GetReportPointAQIRequest();
            AQIPlugin.LN.WSReference.GetReportPointAQIResponse retVal = ((AQIPlugin.LN.WSReference.AirQualityServiceSoap)(this)).GetReportPointAQI(inValue);
            return retVal.GetReportPointAQIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AQIPlugin.LN.WSReference.GetReportPointAQIListResponse AQIPlugin.LN.WSReference.AirQualityServiceSoap.GetReportPointAQIList(AQIPlugin.LN.WSReference.GetReportPointAQIListRequest request) {
            return base.Channel.GetReportPointAQIList(request);
        }
        
        public string[][] GetReportPointAQIList() {
            AQIPlugin.LN.WSReference.GetReportPointAQIListRequest inValue = new AQIPlugin.LN.WSReference.GetReportPointAQIListRequest();
            AQIPlugin.LN.WSReference.GetReportPointAQIListResponse retVal = ((AQIPlugin.LN.WSReference.AirQualityServiceSoap)(this)).GetReportPointAQIList(inValue);
            return retVal.GetReportPointAQIListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AQIPlugin.LN.WSReference.getRJNDResponse AQIPlugin.LN.WSReference.AirQualityServiceSoap.getRJND(AQIPlugin.LN.WSReference.getRJNDRequest request) {
            return base.Channel.getRJND(request);
        }
        
        public string[][] getRJND(string startDate, string enddate) {
            AQIPlugin.LN.WSReference.getRJNDRequest inValue = new AQIPlugin.LN.WSReference.getRJNDRequest();
            inValue.startDate = startDate;
            inValue.enddate = enddate;
            AQIPlugin.LN.WSReference.getRJNDResponse retVal = ((AQIPlugin.LN.WSReference.AirQualityServiceSoap)(this)).getRJND(inValue);
            return retVal.getRJNDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AQIPlugin.LN.WSReference.getZHZSResponse AQIPlugin.LN.WSReference.AirQualityServiceSoap.getZHZS(AQIPlugin.LN.WSReference.getZHZSRequest request) {
            return base.Channel.getZHZS(request);
        }
        
        public string[][] getZHZS(string startDate, string enddate) {
            AQIPlugin.LN.WSReference.getZHZSRequest inValue = new AQIPlugin.LN.WSReference.getZHZSRequest();
            inValue.startDate = startDate;
            inValue.enddate = enddate;
            AQIPlugin.LN.WSReference.getZHZSResponse retVal = ((AQIPlugin.LN.WSReference.AirQualityServiceSoap)(this)).getZHZS(inValue);
            return retVal.getZHZSResult;
        }
    }
}
